colour br0, resn HP0
colour br1, resn HP1
colour br2, resn HP2
colour br3, resn HP3
colour br4, resn HP4
colour br5, resn HP5
colour br6, resn HP6
colour br7, resn HP7
colour br8, resn HP8
colour br9, resn HP9
